import Head from "next/head";
import styles from "@/styles/Header.module.css"
import { HiOutlineMapPin } from "react-icons/hi2";
import { PiPhoneCall } from "react-icons/pi";
import { HiOutlineEnvelope } from "react-icons/hi2";
import { FaFacebook, FaInstagram, FaTiktok, FaYoutube } from "react-icons/fa";
import { IoLogoWhatsapp } from "react-icons/io5";
import Link from "next/link";
import 'animate.css';

// components/Header.js
export default function Header() {
    return (
        <>
        <Head>
            <title>NMW Clinic</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.png" />
        </Head>
        <div className={styles.header}>
            <div className={styles.nav_top}>
                <div className={styles.contact_nav}>
                    <div className={styles.contact_nav_box}>
                        <HiOutlineMapPin />
                        <p>Jl. Petogogan II No.29 RT.008 RW.006, Jakarta Selatan</p>
                    </div>
                    <div className={styles.contact_nav_box}>
                        <PiPhoneCall />
                        <Link href="#"><p>081280360370</p></Link>
                    </div>
                    <div className={styles.contact_nav_box}>
                        <HiOutlineEnvelope />
                        <Link href="#"><p>hello@nmwclinic.co.id</p></Link>
                    </div>
                </div>
                <div className={styles.sosmed_nav}>
                    <p>Ikuti Kami di </p>
                    <div className={styles.sosmed_nav_box}>
                        <Link href=""><FaFacebook/></Link>
                        <Link href=""><FaInstagram/></Link>
                        <Link href=""><FaTiktok/></Link>
                        <Link href=""><FaYoutube/></Link>
                    </div>
                </div>
            </div>
            <div className={styles.nav_bottom}>
                <div className={styles.logo}>
                    <Link href="#">
                        <img src="images/logo.svg"/>
                    </Link>
                </div>
                <div className={styles.menu}>
                    <ul>
                        <li><Link href="/layanan">Layanan</Link></li>
                        <li><Link href="/artikel">Artikel</Link></li>
                        <li><Link href="/cabang">Cabang</Link></li>
                        <li><Link href="/katalog">Katalog</Link></li>
                    </ul>
                </div>
                <div className={styles.login}>
                    <Link href="">
                        <button>Masuk</button>
                    </Link>
                </div>
            </div>
        </div>

        <div className={`${styles.floating_whatsapp}`}>
            <div className={`${styles.text_whatsapp} ${styles.bounce_in_up}`}>
                <span><font>Butuh</font> Bantuan?</span>
            </div>
            <Link href=""><button>Konsultasi Sekarang! <IoLogoWhatsapp /></button></Link>
        </div>
      </>
    );
}