import Head from "next/head";
import styles from "@/styles/Header.module.css"
import { HiOutlineMapPin } from "react-icons/hi2";
import { PiPhoneCall } from "react-icons/pi";
import { HiOutlineEnvelope } from "react-icons/hi2";
import { FaFacebook, FaInstagram, FaTiktok, FaYoutube } from "react-icons/fa";
import { IoLogoWhatsapp } from "react-icons/io5";
import Link from "next/link";
import 'animate.css';

// components/Header.js
export default function Header() {
    return (
        <>
        <Head>
            <title>NMW Clinic</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className={styles.header}>
            <div className={styles.nav_top}>
                <div className={styles.contact_nav}>
                    <div className={styles.contact_nav_box}>
                        <HiOutlineMapPin />
                        <p>Jl. Petogogan II No.29 RT.008 RW.006, Jakarta Selatan</p>
                    </div>
                    <div className={styles.contact_nav_box}>
                        <PiPhoneCall />
                        <a href="#"><p>081280360370</p></a>
                    </div>
                    <div className={styles.contact_nav_box}>
                        <HiOutlineEnvelope />
                        <a href="#"><p>hello@nmwclinic.co.id</p></a>
                    </div>
                </div>
                <div className={styles.sosmed_nav}>
                    <p>Ikuti Kami di </p>
                    <div className={styles.sosmed_nav_box}>
                        <a href=""><FaFacebook/></a>
                        <a href=""><FaInstagram/></a>
                        <a href=""><FaTiktok/></a>
                        <a href=""><FaYoutube/></a>
                    </div>
                </div>
            </div>
            <div className={styles.nav_bottom}>
                <div className={styles.logo}>
                    <a href="#">
                        <img src="images/logo.svg"/>
                    </a>
                </div>
                <div className={styles.menu}>
                    <ul>
                        <li><a href="/layanan">Layanan</a></li>
                        <li><a href="/artikel">Artikel</a></li>
                        <li><a href="/cabang">Cabang</a></li>
                        <li><a href="/katalog">Katalog</a></li>
                    </ul>
                </div>
                <div className={styles.login}>
                    <a href="">
                        <button>Masuk</button>
                    </a>
                </div>
            </div>
        </div>

        <div className={`${styles.floating_whatsapp}`}>
            <div className={`${styles.text_whatsapp} ${styles.bounce_in_up}`}>
                <span><font>Butuh</font> Bantuan?</span>
            </div>
            <Link href=""><button>Konsultasi Sekarang! <IoLogoWhatsapp /></button></Link>
        </div>
      </>
    );
}